# Automatically generated by configure - do not modify
include ../config-host.mak
CONFIG_QEMU_PREFIX="/usr/gnemul/qemu-x86_64"
TARGET_ARCH=x86_64
TARGET_ARCH2=x86_64
TARGET_BASE_ARCH=i386
TARGET_ABI_DIR=x86_64
CONFIG_KVM=y
KVM_CFLAGS=-I/home/jedisty/VSSIM_private/QEMU/kvm/include -I/home/jedisty/VSSIM_private/QEMU/kvm/include/x86
CONFIG_KVM=y
KVM_CFLAGS=-I/home/jedisty/VSSIM_private/QEMU/kvm/include -I/home/jedisty/VSSIM_private/QEMU/kvm/include/x86
USE_KVM_PIT=1
USE_KVM_DEVICE_ASSIGNMENT=1
HWLIB=../libhw64/libqemuhw64.a
TARGET_PHYS_ADDR_BITS=64
CONFIG_SOFTMMU=y
TARGET_XML_FILES=
