/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-x86_64"
#define TARGET_ARCH "x86_64"
#define TARGET_X86_64 1
#define TARGET_I386 1
#define CONFIG_KVM 1
#define CONFIG_KVM 1
#define USE_KVM_PIT 1
#define USE_KVM_DEVICE_ASSIGNMENT 1
#define TARGET_PHYS_ADDR_BITS 64
#define CONFIG_SOFTMMU 1
