######################################################################
# Automatically generated by qmake (1.07a) Thu Aug 9 16:50:33 2012
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form1.ui.h
INTERFACES += form1.ui
SOURCES += main.cpp
