/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_X86_64 1
#define HOST_LONG_BITS 64
#define HAVE_BYTESWAP_H 1
#define CONFIG_SLIRP 1
#define CONFIG_AC97 1
#define CONFIG_ES1370 1
#define CONFIG_SB16 1
#define AUDIO_DRIVERS \
    &oss_audio_driver, \

#define CONFIG_VNC_TLS 1
#define HAVE_FNMATCH_H 1
#define QEMU_VERSION "0.11.0"
#define QEMU_PKGVERSION " (qemu-kvm-0.11.0)"
#define CONFIG_SDL 1
#define CONFIG_CURSES 1
#define CONFIG_ATFILE 1
#define CONFIG_UTIMENSAT 1
#define CONFIG_PIPE2 1
#define CONFIG_SPLICE 1
#define CONFIG_INOTIFY 1
#define CONFIG_CURL 1
#define CONFIG_AIO 1
#define HAVE_IOVEC 1
#define HAVE_PREADV 1
#define CONFIG_signalfd 1
#define CONFIG_eventfd 1
#define CONFIG_UNAME_RELEASE ""
